# -*- coding: utf-8 -*-
"""AtividadeCarlos-26.04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IC4Qt8P6zwcO-8AYIObxrIx4E5JpgfR8
"""



"""IMPORTANDO AS BIBLIOTECAS"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"""IMPORTANDO OS ARQUIVOS"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Atividade01_26.04.csv')
df.head()

"""FAZENDO UM BLOXPLOT ENTRE AS COLUNAS DE GÊNERO E PRESSÃO ARTERIAL"""

sns.boxplot(x='Gender', y='Blood_Pressure', data=df)

sns.boxplot(x='Gender', y='Cholesterol_Level', data=df)

"""  CONCLUSÃO

A análise foi realizada com o objetivo de informar aos órgãos competentes da área da saúde que o índice de incidência de doenças relacionadas ao colesterol alto e à pressão arterial é maior entre os homens do que entre as mulheres.

 - Foi constatado que a incidência de doenças, como hipertensão e níveis elevados de colesterol, é mais alta no sexo masculino.
"""